### ISSUE TITLE
Using Parse-Module to install request module

### ISSUE THREAD

**Issue by chenzhuo8804** [flovilmart/parse-module#1]
Hi I am trying to use parse-module to install request module (https://github.com/request/request)
 but getting following error,
  Result: Error: Failed to load util with: Could not find file util
    at Module.load (parse_modules/require/index.js:74:14)
    at require2 (parse_modules/require/index.js:173:11)
    at parse_modules/require/index.js:151:10
    at eval (eval at <anonymous> (parse_modules/require/index.js:79:8), <anonymous>:18:29)
    at eval (eval at <anonymous> (parse_modules/require/index.js:79:8), <anonymous>:162:4)
    at Module.load (parse_modules/require/index.js:79:3)
    at require2 (parse_modules/require/in... (truncated)
 I am wondering if installing request has been tested ?

**Comment by flovilmart** [comment]
It hasn't been tested and it will never work.
